/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MyRoom2.glb -k 
*/

import {  useGLTF, useVideoTexture } from '@react-three/drei'
import { useMemo, useRef, useState, useEffect } from 'react';
import * as THREE from "three";
import { EffectComposer, Outline, Noise } from "@react-three/postprocessing";
import { BlendFunction } from 'postprocessing'
import { OverrideMaterialManager } from 'postprocessing'
// import Music from '../../Music';
import { useMusic, usePDF, useFilm } from '../../UIStore'
import { useMediaQuery } from "@uidotdev/usehooks";

function convertMaterialsToBasic(materials, alphaTestValue = 0) {
  const newMaterials = {};

  Object.keys(materials).forEach((key) => {
    const oldMaterial = materials[key];
    if (oldMaterial instanceof THREE.MeshStandardMaterial) {
      const newMaterial = new THREE.MeshBasicMaterial({
        map: oldMaterial.map,
        transparent: oldMaterial.transparent,
        alphaTest: oldMaterial.transparent ? 0.1 : alphaTestValue,
      });
      newMaterials[key] = newMaterial;
    } else {
      newMaterials[key] = oldMaterial;
    }
  });

  return newMaterials;
}

export default function Model(props) {
  const isSmallDevice = useMediaQuery("only screen and (max-width : 768px)");
  OverrideMaterialManager.workaroundEnabled = true
  const [hoveredItem, setHoveredItem] = useState();
  const mirror = useRef();
  const songtitle = useRef();
  const buttonpauseone = useRef();
  const actualjournal = useRef();
  const buttonfastforwardone = useRef();
  const buttonplayone = useRef();
  const buttonrewindone = useRef();
  const screenone = useRef();
  const monitorscreen = useRef();
  const cover = useRef();
  const volumedial = useRef();
  const { nodes, materials } = useGLTF('/MyRoom3.glb')
  const newMaterials = convertMaterialsToBasic(materials)

  const video = useVideoTexture('websiteThumbnail08_AV1.mp4', {muted: true, loop: true, playsInline: true})
  const videoDimensions = [1920, 1284]
  video.flipY = false;
  console.log(monitorscreen)

  const outlinedRefs = [actualjournal, monitorscreen]

  const { playMusic, pauseMusic} = useMusic();
  const { openPDF } = usePDF();
  const { openFilm } = useFilm();
  const onMusic = (n) => {
    if (n=="play") {
      playMusic()
    } else if (n=="pause") {
      pauseMusic()
    }
  };
  const onHover = (n, ref) =>{
    if (ref==buttonpauseone) {
      console.log("buttonpauseone")
    } else if (ref==volumedial) {
      console.log("volumedial")
    }
    if (n==1) {
      setHoveredItem(ref);
    } else if (n==0) {
      setHoveredItem(null);
    }
  };
  
  return (
    <>
    <group {...props} dispose={null}>
    <EffectComposer autoClear={false}>
        <Outline selection={isSmallDevice ?  outlinedRefs : hoveredItem } blur={false} edgeStrength={isSmallDevice? 1 : 5} visibleEdgeColor={0xf99b2f} />
        <Noise opacity={0.2} blendFunction={BlendFunction.OVERLAY} />
    </EffectComposer>

      <mesh name="Journal" 
        geometry={nodes.Journal.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.915, 0.896, 0.419]} />
      <mesh name="Room" 
        geometry={nodes.Room.geometry} 
        material={newMaterials.TextureTwoMaterial} 
        position={[0, 1.5, 0]} scale={1.5} />
      <mesh name="Button_FastForward_One" ref={buttonfastforwardone} 
        onPointerEnter={() => onHover(1, buttonfastforwardone)} 
        onPointerLeave={() => onHover(0, buttonfastforwardone)} 
        geometry={nodes.Button_FastForward_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.857, 0.92, 0.066]} rotation={[0, 0.954, -1.773]} />
      <mesh name="Button_Pause_One" ref={buttonpauseone} 
        onPointerEnter={() => onHover(1, buttonpauseone)} 
        onPointerLeave={() => onHover(0, buttonpauseone)} 
        onClick={() => onMusic("pause")} 
        geometry={nodes.Button_Pause_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.857, 0.92, 0.066]} 
        rotation={[0, 0.954, -1.773]} />
      <mesh name="Button_Play_One" ref={buttonplayone} 
        onPointerEnter={() => onHover(1, buttonplayone)} 
        onPointerLeave={() => onHover(0, buttonplayone)} 
        onClick={() => onMusic("play")} 
        geometry={nodes.Button_Play_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.857, 0.92, 0.066]} 
        rotation={[0, 0.954, -1.773]} />
      <mesh name="Button_Rewind_One" ref={buttonrewindone} 
        onPointerEnter={() => onHover(1, buttonrewindone)} 
        onPointerLeave={() => onHover(0, buttonrewindone)} 
        geometry={nodes.Button_Rewind_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.857, 0.92, 0.066]} 
        rotation={[0, 0.954, -1.773]} />
      <mesh name="Screen_One" ref={screenone} 
        onPointerEnter={() => onHover(1, screenone)} 
        onPointerLeave={() => onHover(0, screenone)} 
        geometry={nodes.Screen_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.88, 0.936, 0.077]} 
        rotation={[0, 0.954, -0.202]} />
      <mesh name="Monitor_Screen" ref={monitorscreen} 
        onPointerEnter={() => onHover(1, monitorscreen)} 
        onPointerLeave={() => onHover(0, monitorscreen)} 
        onClick={() => openFilm()}
        geometry={nodes.Monitor_Screen.geometry} 
        // material={newMaterials.Screen} 
        // material={videoTexture} 
        // map = {video}
        toneMapped = {false}
        position={[1.296, 1.17, 0.45]} 
        rotation={[0, 0, -1.79]} >
        <meshBasicMaterial map={video} />
    </mesh>
      <mesh name="Cover" ref={cover} 
        onPointerEnter={() => onHover(1, cover)} 
        onPointerLeave={() => onHover(0, cover)} 
        geometry={nodes.Cover.geometry} 
        material={newMaterials.CD} 
        position={[0.888, 1.029, 0.051]} 
        rotation={[0, 0.954, -0.202]} />
      <mesh name="VolumeDial_One" ref={volumedial} 
        // onPointerEnter={() => onHover(1, volumedial)} 
        // onPointerLeave={() => onHover(0, volumedial)} 
        // onWheel={(e) => onVolume(e)}
        geometry={nodes.VolumeDial_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.828, 0.93, 0.047]} 
        rotation={[0, 0.954, -1.773]} />
      <mesh name="Mirror" ref={mirror} 
        geometry={nodes.Mirror.geometry} 
        position={[-0.986, 1.038, -1.014]} 
        rotation={[Math.PI / 2, 0, 0]} 
        scale={[0.462, 1, 0.73]} >
      </mesh>
      <mesh name="Actual_Journal" ref={actualjournal} 
        onPointerEnter={() => onHover(1, actualjournal)} 
        onPointerLeave={() => onHover(0, actualjournal)} 
        onClick={() => openPDF()}
        geometry={nodes.Actual_Journal.geometry} 
        material={newMaterials.Journal} 
        position={[-0.004, 1.5, 0]} scale={1.5} />
    </group>
    {/* <Music playpause={songPlaying}/> */}
    </>
  )
}

useGLTF.preload('/MyRoom3.glb')
