/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MyRoom2.glb -k 
*/

import {  useGLTF, useTexture, Text } from '@react-three/drei'
import { useRef, useState, useEffect, useMemo } from 'react';
import * as THREE from "three";
import { EffectComposer, Outline, Noise } from "@react-three/postprocessing";
import { BlendFunction } from 'postprocessing'
import { OverrideMaterialManager } from 'postprocessing'
// import Music from '../../Music';
import { useMusic, usePDF, useFilm, useThreeDLoad, useChapter, useEnterWebsite } from '../../UIStore'
import { useMediaQuery } from "@uidotdev/usehooks";
import narratives from '../../narratives.json'
import { useFrame } from '@react-three/fiber';

function convertMaterialsToBasic(materials, alphaTestValue = 0) {
  const newMaterials = {};

  Object.keys(materials).forEach((key) => {
    const oldMaterial = materials[key];
    if (oldMaterial instanceof THREE.MeshStandardMaterial) {
      const newMaterial = new THREE.MeshBasicMaterial({
        map: oldMaterial.map,
        transparent: oldMaterial.transparent,
        alphaTest: oldMaterial.transparent ? 0.1 : alphaTestValue,
      });
      newMaterials[key] = newMaterial;
    } else {
      newMaterials[key] = oldMaterial;
    }
  });

  return newMaterials;
}


export default function Model(props) {
  const {setThreeDLoadedTrue } = useThreeDLoad();
  useEffect(()=>{
    setThreeDLoadedTrue()
  }, []);
  const {selectedChapter} = useChapter();
  const textColor = new THREE.Color(0xe2cfbc)
  const isSmallDevice = useMediaQuery("only screen and (max-width : 768px)");
  OverrideMaterialManager.workaroundEnabled = true
  const [hoveredItem, setHoveredItem] = useState();
  const mirror = useRef();
  // const songtitle = useRef();
  const buttonpauseone = useRef();
  const actualjournal = useRef();
  const buttonfastforwardone = useRef();
  const buttonplayone = useRef();
  const buttonrewindone = useRef();
  const screenone = useRef();
  const monitorscreen = useRef();
  const cover = useRef();
  const volumedial = useRef();
  const { nodes, materials } = useGLTF('/MyRoom3.glb')
  const newMaterials = convertMaterialsToBasic(materials)
  const {enterWebsite, setEnterWebsite} = useEnterWebsite();
  const [video] = useState(() => {
    const vid = document.createElement('video');
    vid.crossOrigin = 'Anonymous';
    vid.loop = true;
    vid.muted = true; // Muted is required by browsers to autoplay
    return vid;
  });
  const videoSrc = 'Thumbnails/websiteThumbnail_01.mp4';

  const [song, setSong] = useState(narratives[selectedChapter-1].songs.track)


  useEffect(() => {
    if (narratives[selectedChapter-1].songs.track.length > 17) {
      setSong(narratives[selectedChapter-1].songs.track.slice(0, 17) + '..');
    } else {
      setSong(narratives[selectedChapter-1].songs.track)
    }
  }, [selectedChapter])

  async function safePlay(video) {
    try {
      // if (isThreeDLoaded) {
        await video.play();
      // }
    } catch (error) {
      console.error("Playback failed or was prevented:", error);
    }
  }
  async function safePause(video) {
    try {
      await video.pause();
    } catch (error) {
      console.error("Playback failed or was prevented:", error);
    }
  }
  async function loadVideo(video) {
    try {
      await video.load();
    } catch(error) {
      console.log(error)
    }
  }
  // const [videoTexture, setVideoTexture] = useState(new THREE.VideoTexture(video));
  const videoTexture = (new THREE.VideoTexture(video)) 

  // 2. Manage the video source and pausing logic
  useEffect(() => {
      safePause(video)
      video.currentTime = 0;

      video.src = `Thumbnails/${narratives[selectedChapter-1].thumbnail}`;
      loadVideo(video)
      
      safePlay(video)
    return () => {
      safePause(video)
    };
  }, [videoSrc, video, selectedChapter]);



  useFrame(() => {
    if (videoTexture) {
      videoTexture.needsUpdate = true;
      videoTexture.flipY = false;
    } 
  });
  const coverImage = useTexture(`Converted Covers/${narratives[selectedChapter-1].songs.cover}`);
  coverImage.flipY = false;

  const outlinedRefs = [actualjournal, monitorscreen]

  const { playMusic, pauseMusic} = useMusic();
  const { openPDF } = usePDF();
  const { openFilm } = useFilm();
  const onMusic = (n) => {
    if (n=="play") {
      playMusic()
    } else if (n=="pause") {
      pauseMusic()
    }
  };
  const onHover = (n, ref) =>{
    if (n==1) {
      setHoveredItem(ref);
    } else if (n==0) {
      setHoveredItem(null);
    }
  };
  
  return (
    <>
    <group {...props} dispose={null}>
    <EffectComposer autoClear={false}>
        <Outline selection={isSmallDevice ?  outlinedRefs : hoveredItem } blur={false} edgeStrength={isSmallDevice? 1 : 5} visibleEdgeColor={0xf99b2f} />
        <Noise opacity={0.2} blendFunction={BlendFunction.OVERLAY} />
    </EffectComposer>

      <mesh name="Journal" 
        geometry={nodes.Journal.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.915, 0.896, 0.419]} />
      <mesh name="Room" 
        geometry={nodes.Room.geometry} 
        material={newMaterials.TextureTwoMaterial} 
        position={[0, 1.5, 0]} scale={1.5} />
      <mesh name="Button_FastForward_One" ref={buttonfastforwardone} 
        onPointerEnter={() => onHover(1, buttonfastforwardone)} 
        onPointerLeave={() => onHover(0, buttonfastforwardone)} 
        geometry={nodes.Button_FastForward_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.857, 0.92, 0.066]} rotation={[0, 0.954, -1.773]} />
      <mesh name="Button_Pause_One" ref={buttonpauseone} 
        onPointerEnter={() => onHover(1, buttonpauseone)} 
        onPointerLeave={() => onHover(0, buttonpauseone)} 
        onClick={() => onMusic("pause")} 
        geometry={nodes.Button_Pause_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.857, 0.92, 0.066]} 
        rotation={[0, 0.954, -1.773]} />
      <mesh name="Button_Play_One" ref={buttonplayone} 
        onPointerEnter={() => onHover(1, buttonplayone)} 
        onPointerLeave={() => onHover(0, buttonplayone)} 
        onClick={() => onMusic("play")} 
        geometry={nodes.Button_Play_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.857, 0.92, 0.066]} 
        rotation={[0, 0.954, -1.773]} />
      <mesh name="Button_Rewind_One" ref={buttonrewindone} 
        onPointerEnter={() => onHover(1, buttonrewindone)} 
        onPointerLeave={() => onHover(0, buttonrewindone)} 
        geometry={nodes.Button_Rewind_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.857, 0.92, 0.066]} 
        rotation={[0, 0.954, -1.773]} />
      <mesh name="Screen_One" ref={screenone} 
        onPointerEnter={() => onHover(1, screenone)} 
        onPointerLeave={() => onHover(0, screenone)} 
        geometry={nodes.Screen_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.88, 0.936, 0.077]} 
        rotation={[0, 0.954, -0.202]} />
      <mesh name="Monitor_Screen" ref={monitorscreen} 
        onPointerEnter={() => onHover(1, monitorscreen)} 
        onPointerLeave={() => onHover(0, monitorscreen)} 
        onClick={() => openFilm()}
        geometry={nodes.Monitor_Screen.geometry} 
        // material={newMaterials.Screen} 
        toneMapped = {false}
        position={[1.296, 1.17, 0.45]} 
        rotation={[0, 0, -1.79]} >
        <meshBasicMaterial map={videoTexture}  />
    </mesh>
      <mesh name="Cover" ref={cover} 
        onPointerEnter={() => onHover(1, cover)} 
        onPointerLeave={() => onHover(0, cover)} 
        geometry={nodes.Cover.geometry} 
        // material={newMaterials.CD} 
        position={[0.888, 1.029, 0.051]} 
        rotation={[0, 0.954, -0.202]} >
        <meshBasicMaterial map={coverImage} />
    </mesh>
      <mesh name="VolumeDial_One" ref={volumedial} 
        // onPointerEnter={() => onHover(1, volumedial)} 
        // onPointerLeave={() => onHover(0, volumedial)} 
        // onWheel={(e) => onVolume(e)}
        geometry={nodes.VolumeDial_One.geometry} 
        material={newMaterials.TextureOneMaterial} 
        position={[0.828, 0.93, 0.047]} 
        rotation={[0, 0.954, -1.773]} />
      <mesh name="Mirror" ref={mirror} 
        geometry={nodes.Mirror.geometry} 
        position={[-0.986, 1.038, -1.014]} 
        rotation={[Math.PI / 2, 0, 0]} 
        scale={[0.462, 1, 0.73]} >
      </mesh>
      <mesh name="Actual_Journal" ref={actualjournal} 
        onPointerEnter={() => onHover(1, actualjournal)} 
        onPointerLeave={() => onHover(0, actualjournal)} 
        onClick={() => openPDF()}
        geometry={nodes.Actual_Journal.geometry} 
        material={newMaterials.Journal} 
        position={[-0.004, 1.5, 0]} scale={1.5} />
      <Text depthOffset={1} color={textColor} clipRect={[0,-1,1,1]} anchorX="left" anchorY="middle" maxWidth={5} whiteSpace='normal' 
        position={[0.850, 0.939, 0.066]} 
        rotation={[-0.3, -0.6, -0.18]} fontSize={0.0065} >
        {song}
      </Text>
    </group>
    {/* <Music playpause={songPlaying}/> */}
    </>
  )
}

useGLTF.preload('/MyRoom3.glb')
